apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-deployment-autoscaling
spec:
  selector:
    matchLabels:
      project: web-application-autoscaling
  template:
    metadata:
      labels:
        project: web-application-autoscaling
    spec:
      containers:
        - name: webapp
          image: elvolver/k8sphp:latest         
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-pod-service-autoscaling
  labels:
    env: prod
    owner: DmitryVolkov
spec:
  selector:
    project: web-application-autoscaling
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

